### ISSUE TITLE
Cannot find icon: ~/.FreeCAD/Mod/Beltrami/Resources/Icons/beltrami.svg

### ISSUE THREAD

**Issue by j-wiedemann** [Simturb/Beltrami#14]
Icons can't be find

`18:44:41  Cannot find icon: ~/.FreeCAD/Mod/Beltrami/Resources/Icons/beltrami.svg
18:44:53  Cannot find icon: ~/.FreeCAD/Mod/Beltrami/Resources/Icons/coldStart.svg
18:44:53  Cannot find icon: ~/.FreeCAD/Mod/Beltrami/Resources/Icons/modif.svg`

```
OS: Ubuntu 20.04.3 LTS (ubuntu:GNOME/ubuntu)
Word size of FreeCAD: 64-bit
Version: 0.20.25645 (Git) AppImage
Build type: Release
Branch: master
Hash: 37d9757399b4c2ec30318eb88d7cd7c508246345
Python version: 3.9.7
Qt version: 5.12.9
Coin version: 4.0.0
OCC version: 7.5.2
Locale: French/France (fr_FR)
```
I think icons folder should be rename to "Icons"
or 
"Icons" occurences in InitGui.py should be replace by "icons"
`---self.__class__.Icon=FreeCAD.getUserAppDataDir()+"Mod"+"/Beltrami/Resources/Icons/beltrami.svg"
+++self.__class__.Icon=FreeCAD.getUserAppDataDir()+"Mod"+"/Beltrami/Resources/icons/beltrami.svg"
`

**Comment by Simturb** [comment]
Thank you for the comment. Issue corrected.
