### ISSUE TITLE
calculate optimum impeller blade pitch, impeller diameter and required impeller blade area ?

### ISSUE THREAD

**Issue by Supermagnum** [Simturb/Beltrami#28]
Perhaps this software could be expanded to calculate optimum impeller blade pitch, impeller diameter and required impeller blade area.

Please read: 
http://www.mh-aerotools.de/airfoils/javaprop.htm

**Comment by Simturb** [comment]
The goal of Beltrami is to generate a blade geometry from parameters compatible with fluid dynamics. The geometry obtained can be submitted to a performance assessment process. It  is generally CFD (Computational Fluid Dynamics). Then a process loop is created by sequences of  modification of geometry and assessment. More generally the size, the rotational speed are based on cavitation behavior and hydraulic conditions. These issues are treated in my web site at https://michelsabourin.scenari-community.org/SimTurbTech/co/1__HydrauliqueBase.html
 To consult in English, be sure to activate your browser translator.
