### ISSUE TITLE
README: having release notes but hiding previous releases in a collapsed div

### ISSUE THREAD

**Issue by luzpaz** [Simturb/Beltrami#31]
Would it be possible to have the release notes (https://github.com/Simturb/Beltrami#release-notes) for latest release showing and then any previous release notes added inside a [collapsed div](https://gist.github.com/pierrejoubert73/902cc94d79424356a8d20be2b382e1ab). This way the README isn't cluttered and the previous changes are accessible with a simple click.

**Comment by Simturb** [comment]
Done
