### ISSUE TITLE
If i already have a 2D blade profile (discrete points), how do you use it?

### ISSUE THREAD

**Issue by siwuxei** [Simturb/Beltrami#33]
Thank you for sharing it. I recently wrote a script for parameterizing turbine blade profiles that generates a 2D blade profile (outputting a set of discrete points). I would like to use Beltrami to create a 3D model. Is this possible?

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Simturb** [comment]
Yes, in your installation directory Beltrami/Examples there is a file ["CascadeRadiale.](https://github.com/Simturb/Beltrami/blob/main/Examples/CascadeRadiale.FCStd) frow which you can start. 
Watch https://www.youtube.com/watch?v=UFdI0RjN6jM with subtitles in English.
Also, may be more clear in this video https://www.youtube.com/watch?v=UFdI0RjN6jM at 12:26, I explain the CascadeRadiale  file in English.

**Comment by siwuxei** [comment]
> Yes, in your installation directory Beltrami/Examples there is a file ["CascadeRadiale.](https://github.com/Simturb/Beltrami/blob/main/Examples/CascadeRadiale.FCStd) frow which you can start. Watch https://www.youtube.com/watch?v=UFdI0RjN6jM with subtitles in English. Also, may be more clear in this video https://www.youtube.com/watch?v=UFdI0RjN6jM at 12:26, I explain the CascadeRadiale file in English.
 
👌 I will try it, thank you for your reply.
