### ISSUE TITLE
coldStart does not produce blade

### ISSUE THREAD

**Issue by bakakouhai** [Simturb/Beltrami#38]
Hello.

I have installed Beltrami via FreeCAD Addons Manager.
However, pressing the ColdStart button, I got this error in Report View Tab:

```
15:11:48  Running the Python command 'coldStart' failed:
Traceback (most recent call last):
  File "/Users/iwan/Library/Application Support/FreeCAD/Mod/Beltrami/./coldStart.py", line 21, in Activated
    pM=Beltrami.beltrami(fp)
  File "/Users/iwan/Library/Application Support/FreeCAD/Mod/Beltrami/./Beltrami.py", line 49, in __init__
    self.traceMeridien(fp)
  File "/Users/iwan/Library/Application Support/FreeCAD/Mod/Beltrami/./Beltrami.py", line 1211, in traceMeridien
    Discretize.Discretization(fpM, (App.ActiveDocument.getObject("IsoCurve"),"Edge"+I))
  File "/Users/iwan/Library/Application Support/FreeCAD/Mod/Curves/./freecad/Curves/Discretize.py", line 48, in __init__
    obj.ParameterFirst = edge.FirstParameter

'NoneType' object has no attribute 'FirstParameter'
```

Here is my FreeCAD info:
OS: macOS 14.4.1
Word size of FreeCAD: 64-bit
Version: 0.21.2.33771 (Git)
Build type: Release
Branch: (HEAD detached at 0.21.2)
Hash: b9bfa5c5507506e4515816414cd27f4851d00489
Python 3.10.13, Qt 5.15.8, Coin 4.0.0, Vtk 9.2.6, OCC 7.6.3
Locale: C/Default (C)

The Addon Manager installed Beltrami 1.0.8 Alpha with Curve 0.6.38

There are some lines created, from what I understand, they are used for projection purpose.
The meridian plane is created, however, there is no blade model as seen below:
<img width="1440" alt="Screenshot 2024-06-09 at 15 20 33" src="https://github.com/Simturb/Beltrami/assets/39821914/500f0ccf-2365-4c3f-bfd3-052e8c570522">

Regards,
Iwan

**Comment by Simturb** [comment]
Thanks for your issue, you are right. It was working before this last FreeCAD version 0.21.2. Give me few days. I will look at it.
Michel

**Comment by Simturb** [comment]
Issue solved by Chris in his Curves workbench.
